/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const GalleryCategory = IDL.Variant({
  'journey' : IDL.Null,
  'farm' : IDL.Null,
  'vineyard' : IDL.Null,
  'lifestyle' : IDL.Null,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
  'category' : GalleryCategory,
});

export const idlService = IDL.Service({
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getContactSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getGalleryItemsByCategory' : IDL.Func(
      [GalleryCategory],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const GalleryCategory = IDL.Variant({
    'journey' : IDL.Null,
    'farm' : IDL.Null,
    'vineyard' : IDL.Null,
    'lifestyle' : IDL.Null,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
    'category' : GalleryCategory,
  });
  
  return IDL.Service({
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getContactSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getGalleryItemsByCategory' : IDL.Func(
        [GalleryCategory],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };